import { Client, ClientPoints, Reward, Database, ClientType, OrderLog } from '../types';
import { REWARDS_DATA } from './rewards_data';

const DB_KEY = 'gulf_prolub_db_v41';
const GLOBAL_ORDER_HISTORY_KEY = 'gulf_prolub_global_orders_v1';
const DEFAULT_POINTS = 0; 

const RAW_CLIENTS_CSV = `Tipo de cliente;Id;Punto de venta;Contraseña
Normal;3648;COLMENARES CELY MARIA DE JESUS;362
Normal;2288;TECNILUBRICANTES GYG S.A.S;167
Normal;2816;AGROFILTER LTDA;439
Normal;3415;SMART & GREEN ENERGY S.A.S.;402
Normal;7400;CARO CASTELBLANCO LUIS ALEJANDRO;178
Normal;9309;HUERTAS ORTEGA CESAR MANUEL;238
Normal;5663;JEREZ BUITRAGO JHON FREDY;223
Normal;3005;DACAR FILTROS S.A.S.;494
Normal;9643;PRIETO CARDENAS RONAL FABIAN;209
Normal;2744;ANAYA OLIVEROS DIANA FERNANDA;126
Normal;5489;FC POWER SOLUTIONS SAS;318
Normal;8915;SILVA VARGAS FABIO EDUARDO;126
Normal;7209;COMERCIALIZADORA FILT REP LTDA;463
Normal;2431;RIVAS MARTINEZ CARLOS EDUARDO;425
Normal;1358;MATALLANA BALLESTEROS MAURICIO ANTONIO;417
Normal;3886;DOSMOPAR SOCIEDAD POR ACCIONES SIMPLIFICADA;286
Normal;1533;MOLANO BARRIOS LAURA MELISSA;114
Normal;7869;GARCIA REYES GONZALO EDUARDO;179
Normal;1666;BERNAL PACHON GERMAN ALONSO;328
Normal;7882;LUBRISERVICIOS RETEN SUR S.A.S;350
Normal;2407;TECNI.MOTOS GL S.A.S.;284
Normal;7261;COMERCIALIZADORA INTERNACIONAL CALITRADE SOCIEDAD POR ACCIONES S;265
Normal;6100;AGROFILTRACIONES R.M. SAS;296
Normal;8254;FILTROS Y ACEITES SANTA MARTA S.A.S.;498
Normal;9279;GOMEZ RODRIGUEZ FERNANDO;376
Normal;3573;MELO OLMOS SERGIO ANDRES;442
Normal;3484;AMERICAN FILTERS OIL SAS;247
Normal;5373;ROZO MORA JORGE ALGEMIRO;297
Normal;8124;GRAND FILTERS EU;114
Normal;1370;CALDERON URREGO ANDRES ARTURO;313
Normal;4003;TECNIAUTOAMERICANA S.A.S.;388
Normal;9600;LUBRICANTES VALLADOLID S.A.S.;417
Normal;3582;COLOMBIANA DE ACEITES Y FILTROS INDUSTRIALES S.A.S;368
Normal;6150;ROJAS PEREZ JOSE ORLANDO;278
Normal;5306;BRAVO GRISALES LUZ DERLY;221
Normal;2444;PIRACOCA JIMENEZ HECTOR EMILIO;105
Normal;9766;GUALTEROS LOVERA FERNANDO;225
Normal;1561;MURCIA ALBORNOZ JUAN PABLO;137
Normal;6041;LUBRICANTES GARCIA NOPE SAS;156
Normal;5451;DONDE ALEJO LUBRICENTRO SAS;231
Normal;5102;CORO JORGE IVAN;344
Normal;5898;PAULO RICHARD RAMOS DAZA;257
Normal;9856;OSCAR FERNANDO PEÑA GUTIERREZ;446
Normal;1625;GOMEZ CERON ARCELINA MARGOTH;133
Normal;3861;SUAREZ OJEDA IVAN RICARDO;440
Normal;2618;RAMIREZ MIRQUEZ MOISES;149
Normal;5535;SILVA LOPEZ OSCAR IVAN;257
Normal;2253;HERNANDEZ SACRISTAN FABIAN ROLANDO;136
Normal;1968;SALINAS REYES GESLY YURANY;308
Normal;1621;BIOFILTER LTDA;174
Normal;4791;RODRIGUEZ PULIDO LUZ DARY;411
Normal;4290;QUINTANA RIASCOS JOSE FERNANDO;330
Normal;2335;MONTACARGAS EN SIBERIA S A S;351
Normal;4435;LUBRICANTES LA ROCA S.A.S;229
Normal;2720;DOCEL RAMIREZ JUAN CARLOS;210
Normal;1886;SANCHEZ PALACIO ANGEL HUMBERTO;443
Normal;4368;LUBRICANTES Y FILTROS LA SEXTA AVENIDA S.A.S.;163
Normal;9164;MASFILTER Y LUBRICANTES SAS;115
Normal;6783;DIRECCIONES HIDRAULICAS EL MONO SAS;317
Normal;1069;JARAMILLO QUINTERO JAIRO;474
Normal;1055;FIZA S A S;296
Normal;5963;VALLES ABELLO ARMANDO;208
Normal;3051;LUBRIMOTOR GRASAS Y ACEITES S.A.S LUBRIMOTOR S.A.S;260
Normal;1247;PEREZ BAUTISTA FRANCISCO ALEJANDRO;253
Normal;8989;GONZALEZ MATAMOROS MARIA DEL TRANSITO;441
Normal;8437;DISTRIBUIDORA DE FILTROS Y LUBRICANTES SR LTDA;104
Normal;7501;PARADA BEATRIZ;480
Normal;7247;GALARZA CARDONA ANDRES FELIPE;446
Normal;6276;RODRIGUEZ TROCHEZ ENELIA;175
Normal;1202;LUBRICENTRO SANTA ROSA SAS;364
Normal;8287;ALBERTO TORRES CARLOS ALFREDO;294
Normal;8658;DIAZ PINZON LUIS FERNANDO;296
Normal;4896;TRANSPORTES Y SERVICIOS INTEGRAL S.A.S;120
Normal;4658;ELECTRICOS Y FERRETERIA GERVEL & COMPAÑIA LTDA;193
Normal;3629;MERCADO RAMIREZ JHON WAYNER;454
Normal;6542;FILTROS Y LUBRICANTES H Y H SAS;148
Normal;8832;VILLANUEVA JAMIR;155
Normal;1922;S.S. UP INVERSIONES SAS;300
Normal;9997;G & O CAMBIO Y DISTRIBUCION DE ACEITE MONTALLANTAS SAS;174
Normal;2810;COMERCIALIZADORA FILT REP LTDA;189
Normal;7887;ESCOBAR CARDONA CESAR AUGUSTO;166
Normal;9054;HERNANDO RINCON CABRA;403
Normal;3330;CASA DEL FILTRO CHÍA S.A.S;430
Normal;3984;RINCON MORENO BRAYAN EDUARDO;477
Normal;7129;LUBRIMARKET FILTROS Y LUBRICANTES SAS;380
Normal;7515;AREVALO CABRA WILMER;489
Normal;9702;TRATERCOL INGENIERIA DE TRATAMIENTOS TERMICOS S.A.S.;395
Normal;8403;MORALES MARTINEZ LEIDY MARCELA;392
Normal;2884;REPRESENTANTE SEGURIDAD GAS S. A. S.;491
Normal;2589;GUERRERO DIAZ CARLOS AUGUSTO;302
Normal;1452;INDUSTRIAS CARDENAS FIRE SAS;435
Normal;6586;SALAS ROSERO EDITH LUCIA;197
Normal;2378;FERRETERIA INDUSTRIAL SOLUFER S.A.S.;282
Normal;6216;LINARES CABRA RUTH ADRIANA;395
Normal;2253;RODRIGUEZ PULIDO ANA BELISA;280
Normal;3795;ALVAREZ RUIZ LILIANA;295
Normal;8697;TECNOLUBES SAS;222
Normal;7064;CRUZ AVILA JOSE JOAQUIN;307
Normal;6295;ZAPATA GIRALDO MARTHA ROCIO;373
Normal;4343;CIFUENTES SABOGAL PLUTARCO;327
Normal;5266;MONTES GUILLERMO ALVARO JOSE;321
Normal;3497;CORTES SANCHEZ GUSTAVO ADOLFO;183
Normal;8886;PEREZ SEGURA JOSE EDUARDO;435
Normal;7761;CENTRO DE MANTENIMIENTO AUTOMOTRIZ RD S.A.S.;275
Normal;3616;COOPERATIVA DE TRANSPORTADORES FLOTA PALMIRA;105
Normal;9104;DISTRIGAUSDA SAS;349
Normal;5834;MOLINA TORRES NIDIA ESPERANZA;243
Normal;1462;RIGO AUTOS CALI S.A.S;165
Normal;4743;SERVITECA LUBRITECA 15 B S.A.S.;159
Normal;6132;MERLO VANEGAS FLOR CRISTINA;320
Normal;8399;CERON BUITRON PASTOR;133
Normal;9577;LYC LUBRICANTES SAS;292
Normal;3880;PRIETO CANTE CRISTIAN CAMILO;122
Normal;4854;LOPEZ DIAZ GUSTAVO;250
Normal;9881;HERNANDEZ ORTIZ LISSETTE;133
Normal;3978;ROJAS GUATUSMAL BRENDA JOHANA;122
Normal;2941;RIVERA BRAVA S.A.S.;321
Normal;4619;OCAMPO BARRAGAN YESMIN CRISTINA;361
Normal;3645;BECERRA LEON LUZ DARY;439
Normal;2456;TRIANA ROJAS ANA CLOVIS;392
Normal;3169;MUNDIAL DE FILTROS Y AUTOPARTESSAGA SAS;288
Normal;8975;BEJARANO RAMOS LUZ ANGELICA;277
Normal;9874;SERVICIOS INTEGRALES EN LUBRICACIÓN DE MAQUINARIA S.A.S.;481
Normal;5859;BAREÑO FRANCO ELVER RICARDO;496
Normal;5634;GUZMAN GOMEZ NESTOR DARIO;477
Normal;1276;NEWMAN´S CARS SAS;421
Normal;8593;SAAVEDRA GONZALEZ JHON JAIRO;337
Normal;3951;SU PROVEEDOR SUMINISTROS Y FERRETERIA S.A.S;378
Normal;2093;ARIESCA FILTROS & LUBRICANTES S.A.S;458
Normal;7655;DAZA GOMEZ JONATHAN SMITH;430
Normal;1644;RINCON RIVEROS ORLANDO;411
Normal;1139;GONZALEZ SALINAS JEIMMY CAROLINA;109
Normal;7395;HIDRAULICOS J R S A S;413
Normal;6673;AUTOPARTES J&M SUÁREZ S.A.S;335
Normal;3925;HC SERVICE ´S SAS;418
Normal;5440;FORTALEZA CENTRO DE LUBRICACION SAS;466
Normal;5378;ZAPATA GAMBINO WILSON JAVIER;417
Normal;9175;GOMEZ ESPITIA NELSON ARMANDO;451
Normal;6885;TRANSPORTES LIMICIO LTDA;161
Normal;1135;AGROFILTER DE LA SABANA SAS;194
Normal;3829;GUTIERREZ ROJAS JOHAN FELIPE;395
Normal;9771;LEON MOYANO JAVIER MAURICIO;373
Normal;2688;LUBRICANTES SAN ANTONIO SAS;305
Normal;9084;OCCIDENTAL DE SERVICIOS Y REPUESTOS AAA SAS;315
Normal;9493;GALEANO VELASQUEZ MARIA DACIER;145
Normal;4604;RAUL CASAÑAS PALACIOS;377
Normal;6131;FLOREZ VENEGAS JUAN CARLOS;398
Normal;8742;SIERRA MARTINEZ JOHN ALEJANDRO;460
Normal;9905;VILLAMIL MARTINEZ JONATHAN;495
Normal;5078;ABASTECEDORA NACIONAL DE ESTIBAS ANALDES S A;401
Normal;3026;HERNANDEZ NIÑO LEOPOLDO;387
Normal;4045;EDS TISQUESUSA S.A.S;412
Normal;3837;VARGAS VASQUEZ MARY LUZELLA;237
Normal;9146;MORALES GONZALEZ OCTAVIO;154
Normal;4337;PRADA EDWIN CAMILO;481
Normal;1480;TORNIFRENOS Y REPUESTOS OSORIO S.A.S.;248
Normal;3793;RODRIGUEZ QUIROGA JOSE ALEXANDER;197
Normal;1479;GUZMAN ROJAS JUAN SEBASTIAN;128
Normal;6714;RODRIGUEZ ROMERO TANIA MARCELA;171
Normal;3901;GOMEZ LEDESMA LUIS ARMANDO;356
Normal;2614;COLOMBIANA DISTRIBUIDORA DE LUBRICANTES SAS;121
Normal;4187;CRUZ OCHOA JULIO CESAR;394
Normal;7573;LUBRICANTES Y BATERIAS WILCARS SAS;134
Normal;2321;CAPERA LIDIA;221
Normal;2443;SALDARRIAGA & CIA LTDA;129
Normal;2991;CAICEDO CAÑON INGRID MADALAIN;178
Normal;9218;INSTITUTO TECNICO DE EDUCACION LABORAL Y MECANICO DE OCCIDENTE S;236
Normal;6403;GONZALEZ SUAREZ LUIS ALFREDO;435
Normal;1646;VISUM Y CIA LTDA;404
Normal;6401;TRUCK FILERS JM S.A.S;185
Normal;5581;QUINTERO KAREN ARABELLY;427
Normal;3488;NIÑO ZAPATA BRYANT ESTIVEN;143
Normal;6602;BOBCAT SERVICE SAS;214
Normal;2901;ARMERO MORALES SANDRA MILENA;210
Normal;4393;TIBAVISCO VELOZA SERGIO LEONARDO;336
Normal;9719;FILTROS AYZ S.A.S.;336
Normal;1211;PARRA GOMEZ SERGIO GIOVANY;324
Normal;9164;NEIRA LOPEZ LEONARDO MIGUEL;245
Normal;4480;NELCAR DE OCCIDENTE S.A.S;120
Normal;6361;VARGAS MARTINEZ ISMAEL ANTONIO;404
Normal;8314;CENTRO DE LUBRICACION AUTOMOTRIZ S.A.S.;375
Normal;7680;DIAZ MORENO OLGA PATRICIA;312
Normal;5630;TORRES MORALES PAOLA ANDREA;315
Normal;3115;BARRETO OCHOA ROBERT ALBERTO;347
Normal;3234;RODRIGUEZ SILVA JAZMIN LORENA;468
Normal;8959;BAQUERO LARA SILVIA NOHELBA;477
Normal;6465;NUÑEZ MONROY ARMANDO;281
Normal;4844;RODRIGUEZ BONILLA SORAIDA;452
Normal;3291;LUBRIMARKAS R&D S.A.S;211
Normal;5061;GARCIA MARTINEZ EDWIN ALEXANDER;402
Normal;2538;DAZA BARBOSA CRISTIAN CAMILO;352
Normal;5338;CUTA QUINTANA PEDRO ALONSO;153
Normal;2709;MONGUI MEDINA JUAN CARLOS;229
Normal;5984;SANCHEZ BARON MIGUEL ANTONIO;115
Normal;8790;CARDENAS LOPEZ VIVIANA ANDREA;282
Normal;7453;GUZMAN PINEDA YENIFFER;484
Normal;1398;ALONSO GONZALEZ GONZALEZ;414
Normal;2245;LOPEZ GONZALEZ LUIS FERNANDO;299
Normal;3397;PANQUEVA MONTOYA PATRICIO JAVIER;184
Normal;4998;RINCON MONTOYA NELSON ENRIQUE;427
Normal;1899;SANCHEZ AMAGUAÑA FABIAN JAIR;136
Normal;5812;MONTACARGAS HARD CARGO SAS;107
Normal;9261;MKTRONICA CAR SERVICE S.A.S;316
Normal;3827;SERRANO CELY VELKYS SARIMA;273
Normal;2520;AREVALO LOPEZ WALTER;395
Normal;9304;OPERADOR LOGISTICO DG S.A.S;421
Normal;9959;GUAYACAN GUEVARA ALBA INES;342
Normal;4546;VARGAS GONZALEZ LUIS NELSON;319
Normal;8115;SILVA BARBOSA BRIYITH NATALY;423
Normal;4963;CONTRERAS MORENO LUZ ANGELA;342
Normal;9699;TECNIPLANTAS AIRES Y BOMBAS SAS;137
Normal;8419;LOSADA VALLEJO NICXON ALEJANDRO;332
Normal;5145;MONTAÑO BAHAMON JULIAN DAVID;280
Normal;6365;GOMEZ SALAZAR JOHN EDGAR;127
Normal;8972;QUIROGA LEON RUTH NEYLA;406
Normal;5982;ESCOBAR FRANCO JORGE HERMINSUL;172
Normal;8032;GALINDO JULIO CESAR;203
Normal;5534;GOMEZ MESSA JULIAN;221
Normal;6735;GALEANO ALARCON MARCELA;268
Normal;6169;CARDENAS MUÑOZ FLOR DE MARIA;474
Normal;5726;MORENO CABALLERO NINA;286
Normal;2916;CASTRO PARADA HELMER ERNESTO;402
Normal;7844;LOSADA PACHON JOSE DANIEL;445
Normal;7095;ARAGON HENAO FERNANDO ANDRES;146
Normal;3527;ZAMORA VASQUEZ ELIECER;192
Normal;1417;CUEVAS RODRIGUEZ YESID ADRIAN;474
Normal;9031;LUBRIFILTROS MJ SAS;261
Normal;5549;UMAÑA MARTINEZ VICTOR SAMIR;309
Normal;9949;SERVICIOS AUTOMOTORES FLORIDA S.A.S.;387
Normal;8166;FERNANDEZ PAYA ROSO FRANCISCO;457
Normal;1094;NIETO SOLANO LIZETH PAOLA;261
Normal;7012;GONZALEZ SANNA ERICK;356
Normal;9608;BENAVIDES SIERRA DANIEL ANDRES;283
Normal;4532;AUTOVOL PROFESSIONAL S.A.S;493
Normal;5090;LUBRICANTES G.V. SAS;261
Normal;7795;MORENO CUCAITA JHON FREDDY;316
Normal;1766;QUIROGA PAEZ NORBEY ALBERTO;158
Normal;3289;AYALA BERNAL JOSE MESIAS;136
Normal;6776;SERVITECH GROUP SAS;232
Normal;9300;LOPEZ FORERO CRISTIAN CAMILO;127
Pareto;4781;LUBRICANTES LA ESTRELLA FACA S.A.S.;701
Pareto;2842;COOPERATIVA VALLECAUCANA DE TRANSPORTADORES;855
Pareto;7436;LUBRICANTES CZ S.A.S.;558
Pareto;3141;FILTROS Y FILTROS S.A.S.;800
Pareto;6102;GRISALES MESA EDWARD HERNAN;637
Pareto;6761;ROMERO BONILLA MARIN;535
Pareto;9598;DISTRIBUIDORA HERCA ASOCIADOS SAS;951
Pareto;5628;COOPERATIVA INTEGRAL DE TRANSPORTADORES TAXIS EL TRIUNFO;501
Pareto;5953;HOLGIN DIAZ ADALBERTO;822
Pareto;8458;WM FILTERS SAS;961
Pareto;9951;FILCENTER S A S;959
Pareto;5891;PRO-MOTORS S A S;740
Pareto;8677;PEREZ PLAZAS YILMER;538
Pareto;8170;LUBRIREPUESTOS YUMBO JRC S.A.S;723
Pareto;4397;RATIVA ORLANDO ALBERTO;795
Pareto;1142;TRACTOCAD S EN C S;777
Pareto;4517;AMAYA BERNAL VICTOR ANTONIO;930
Pareto;9097;GOMEZ CERON LUDIVIA;874
Pareto;2071;DISTRIBUCIONES ALVARO CORREA S.A.S.;747
Pareto;7832;LUBRICANTES PEPO S.A.S;697
Pareto;8143;INDUSTRIA SUPERFILT S.A.S;909
Pareto;7191;CERON OCHOA MAGNOLIA;912
Pareto;2133;LUBRICANTES Y FILTROS J J S.A.S;857
Pareto;9931;DISTRIBUIDORA IMALBESTOS SAS;823
Pareto;2822;LUBRIKARS S.A.S;604
Pareto;2799;VELASCO VEGA AURA STELLA;858
Pareto;2929;MAX OIL SAS;597
Pareto;5550;GASODISEL SABANA S.A.S;870
Pareto;2468;G C FILTERS SAS;530
Pareto;3793;GONZALEZ SALINAS EDWIN ARLEY;558
Pareto;6300;LUBRIPARTS LYL S.A.S;891
Pareto;6800;AUTOFILTROS Y PARTES GONZA MOTORS SAS;807
Pareto;4374;SERVILLANTAS JAMUNDI S.A.S;745
Pareto;4903;INGEFILTERS COLOMBIA SAS;885
Pareto;9808;HERRERA QUINTERO VICTOR ALONSO;684
Pareto;3237;LUBRICANTES DIDAMAR S.A.S;749
Pareto;3456;VARGAS SALAMANCA LUIS ANGEL;927
Pareto;9790;MARTEXA C I S A S;920
Pareto;7561;DACAR FILTROS S.A.S.;978
Pareto;6931;INVERSIONES BOGOTA MOTORS SAS;876
Pareto;9731;IBAÑEZ ALFONSO EFRAIN;821
Normal;0527;PRUEBA JUAN;000`;

const RAW_POINTS_CSV = `Punto de venta;Puntos disponibles
ZAPATA GIRALDO MARTHA ROCIO;23
ZAPATA GAMBINO WILSON JAVIER;6
ZAMORA VASQUEZ ELIECER;8
VISUM Y CIA LTDA;0
VILLANUEVA JAMIR;35
VILLAMIL MARTINEZ JONATHAN;7
VARGAS VASQUEZ MARY LUZELLA;5
VARGAS MARTINEZ ISMAEL ANTONIO;0
VARGAS GONZALEZ LUIS NELSON;0
VALLES ABELLO ARMANDO;73
UMAÑA MARTINEZ VICTOR SAMIR;0
TRUCK FILERS JM S.A.S;10
TRIANA ROJAS ANA CLOVIS;66
TRANSPORTES Y SERVICIOS INTEGRAL S.A.S;72
TRANSPORTES LIMICIO LTDA;0
TORRES MORALES PAOLA ANDREA;11
TORNIFRENOS Y REPUESTOS OSORIO S.A.S.;45
TIBAVIZCO VELOZA SERGIO LEONARDO;33
TECNOLUBES SAS;0
TECNIPLANTAS AIRES Y BOMBAS SAS;19
SU PROVEEDOR SUMINISTROS Y FERRETERIA S.A.S;0
SILVA LOPEZ OSCAR IVAN;0
SILVA BARBOSA BRIYITH NATALY;0
SIERRA MARTINEZ JOHN ALEJANDRO;0
SERVITECH GROUP SAS;0
SERVITECA LUBRITECA 15 B S.A.S.;31
SERVICIOS INTEGRALES EN LUBRICACIÓN DE MAQUINARIA S.A.S.;0
SERVICIOS AUTOMOTORES FLORIDA S.A.S.;4
SERRANO CELY VELKYS SARIMA;6
SANCHEZ PALACIO ANGEL HUMBERTO;19
SANCHEZ BARON MIGUEL ANTONIO;12
SANCHEZ AMAGUAÑA FABIAN JAIR;3
SALINAS REYES GESLY YURANY;46
SALDARRIAGA & CIA LTDA;18
SALAS ROSERO EDITH LUCIA;0
SAAVEDRA GONZALEZ JHON JAIRO;119
ROZO MORA JORGE ALGEMIRO;44
ROJAS PEREZ JOSE ORLANDO;251
ROJAS GUATUSMAL BRENDA JOHANA;28
RODRIGUEZ TROCHEZ ENELIA;0
RODRIGUEZ SILVA JAZMIN LORENA;0
RODRIGUEZ ROMERO TANIA MARCELA;48
RODRIGUEZ QUIROGA JOSE ALEXANDER;16
RODRIGUEZ PULIDO LUZ DARY;20
RODRIGUEZ PULIDO ANA BELISA;61
RODRIGUEZ BONILLA SORAIDA;0
RIVERA BRAVA S.A.S.;240
RINCON MORENO BRAYAN EDUARDO;20
RINCON MONTOYA NELSON ENRIQUE;0
RIGO AUTOS CALI S.A.S;20
RAUL CASAÑAS PALACIOS;0
RAMIREZ MIRQUEZ MOISES;84
QUIROGA PAEZ NORBEY ALBERTO;0
QUIROGA LEON RUTH NEYLA;0
QUINTERO KAREN ARABELLY;36
QUINTANA RIASCOS JOSE FERNANDO;71
PRIETO CARDENAS RONAL FABIAN;88
PRIETO CANTE CRISTIAN CAMILO;26
PRADA EDWIN CAMILO;26
PEREZ SEGURA JOSE EDUARDO;25
PEREZ BAUTISTA FRANCISCO ALEJANDRO;0
PAULO RICHARD RAMOS DAZA;164
PARRA GOMEZ SERGIO GIOVANY;35
PARADA BEATRIZ;34
PANQUEVA MONTOYA PATRICIO JAVIER;12
OPERADOR LOGISTICO DG S.A.S;0
OCAMPO BARRAGAN YESMIN CRISTINA;72
NUÑEZ MONROY ARMANDO;17
NIÑO ZAPATA BRYANT ESTIVEN;28
LIZETH PAOLA NIETO SOLANO;6
NEWMAN´S CARS SAS;19
NELCAR DE OCCIDENTE S.A.S;16
NEIRA LOPEZ LEONARDO MIGUEL;13
MURCIA ALBORNOZ JUAN PABLO;122
MUNDIAL DE FILTROS Y AUTOPARTESSAGA SAS;36
MORENO CUCAITA JHON FREDDY;0
MORENO CABALLERO NINA;4
MORALES MARTINEZ LEIDY MARCELA;0
MORALES GONZALEZ OCTAVIO;0
MONTES GUILLERMO ALVARO JOSE;33
MONTAÑO BAHAMON JULIAN DAVID;25
MONTACARGAS HARD CARGO SAS;220
MONTACARGAS EN SIBERIA S A S;220
MONGUI MEDINA JUAN CARLOS;0
MOLINA TORRES NIDIA ESPERANZA;0
LAURA MELISSA MOLANO BARRIOS;311
MKTRONICA CAR SERVICE S.A.S;0
MERLO VANEGAS FLOR CRISTINA;25
MERCADO RAMIREZ JHON WAYNER;59
MELO OLMOS SERGIO ANDRES;48
MASFILTER Y LUBRICANTES SAS;55
LYC LUBRICANTES SAS;0
LUBRIMOTOR GRASAS Y ACEITES S.A.S LUBRIMOTOR S.A.S;15
LUBRIMARKET FILTROS Y LUBRICANTES SAS;107
LUBRIMARKAS R&D S.A.S;8
LUBRIFILTROS MJ SAS;0
LUBRICENTRO SANTA ROSA SAS;16
LUBRICANTES Y BATERIAS WILCARS SAS;32
LUBRICANTES VALLADOLID S.A.S.;112
LUBRICANTES LA ROCA S.A.S;65
LUBRICANTES GARCIA NOPE SAS;141
LUBRICANTES G.V. SAS;3
LOSADA VALLEJO NICXON ALEJANDRO;15
LOSADA PACHON JOSE DANIEL;0
LOPEZ GONZALEZ LUIS FERNANDO;0
LOPEZ FORERO CRISTIAN CAMILO;0
LOPEZ DIAZ GUSTAVO;19
LINARES CABRA RUTH ADRIANA;0
JARAMILLO QUINTERO JAIRO;17
INSTITUTO TECNICO DE EDUCACION LABORAL Y MECANICO DE OCCIDENTE S;21
HIDRAULICOS J R S A S;93
HERNANDO RINCON CABRA;62
HERNANDEZ SACRISTAN FABIAN ROLANDO;50
HERNANDEZ ORTIZ LISSETTE;0
HERNANDEZ NIÑO LEOPOLDO;0
HC SERVICE ´S SAS;0
GUZMAN ROJAS JUAN SEBASTIAN;18
GUZMAN PINEDA YENIFFER;3
GUZMAN GOMEZ NESTOR DARIO;25
GUAYACAN GUEVARA ALBA INES;0
GUALTEROS LOVERA FERNANDO;23
GONZALEZ SUAREZ LUIS ALFREDO;82
GONZALEZ SANNA ERICK;0
GONZALEZ SALINAS JEIMMY CAROLINA;85
GONZALEZ MATAMOROS MARIA DEL TRANSITO;0
GOMEZ SALAZAR JOHN EDGAR;3
GOMEZ RODRIGUEZ FERNANDO;87
GOMEZ MESSA JULIAN;0
GOMEZ LEDESMA LUIS ARMANDO;29
GOMEZ ESPITIA NELSON ARMANDO;0
GOMEZ CERON ARCELINA MARGOTH;59
GARCIA REYES GONZALO EDUARDO;161
GARCIA MARTINEZ EDWIN ALEXANDER;13
GALINDO JULIO CESAR;0
GALEANO ALARCON MARCELA;0
GALARZA CARDONA ANDRES FELIPE;21
G & O CAMBIO Y DISTRIBUCION DE ACEITE MONTALLANTAS SAS;60
FORTALEZA CENTRO DE LUBRICACION SAS;31
FLOREZ VENEGAS JUAN CARLOS;25
FIZA S A S;0
FILTROS Y LUBRICANTES H Y H SAS;50
FILTROS Y ACEITES SANTA MARTA S.A.S.;260
FILTROS AYZ S.A.S.;0
SOLUFER S.A.S;40
FERNANDEZ PAYA ROSO FRANCISCO;4
FC POWER SOLUTIONS SAS;182
ESCOBAR FRANCO JORGE HERMINSUL;0
ESCOBAR CARDONA CESAR AUGUSTO;0
ELECTRICOS Y FERRETERIA GERVEL & COMPAÑIA LTDA;0
EDS TISQUESUSA S.A.S;10
DOSMOPAR SOCIEDAD POR ACCIONES SIMPLIFICADA;58
DONDE ALEJO LUBRICENTRO SAS;4
DISTRIGAUSDA SAS;14
DISTRIBUIDORA DE FILTROS Y LUBRICANTES SR LTDA;330
DIAZ PINZON LUIS FERNANDO;417
DIAZ MORENO OLGA PATRICIA;0
DAZA GOMEZ JONATHAN SMITH;18
DAZA BARBOSA CRISTIAN CAMILO;6
CUTA QUINTANA PEDRO ALONSO;0
CUEVAS RODRIGUEZ YESID ADRIAN;0
CRUZ OCHOA JULIO CESAR;7
CRUZ AVILA JOSE JOAQUIN;7
CORTES SANCHEZ GUSTAVO ADOLFO;39
CORO JORGE IVAN;29
COOPERATIVA DE TRANSPORTADORES FLOTA PALMIRA;121
CONTRERAS MORENO LUZ ANGELA;0
COMERCIALIZADORA FILT REP LTDA;279
COLOMBIANA DISTRIBUIDORA DE LUBRICANTES SAS;0
COLOMBIANA DE ACEITES Y FILTROS INDUSTRIALES S.A.S;0
CIFUENTES SABOGAL PLUTARCO;46
CERON BUITRON PASTOR;12
CENTRO DE MANTENIMIENTO AUTOMOTRIZ RD S.A.S.;0
CENTRO DE LUBRICACION AUTOMOTRIZ S.A.S.;208
CASTRO PARADA HELMER ERNESTO;0
CASA DEL FILTRO CHÍA S.A.S;133
CARDENAS MUÑOZ FLOR DE MARIA;29
CARDENAS LOPEZ VIVIANA ANDREA;24
CAPERA LIDIA;3
CAICEDO CAÑON INGRID MADALAIN;11
BRAVO GRISALES LUZ DERLY;132
BOBCAT SERVICE SAS;151
BIOFILTER LTDA;69
BERNAL PACHON GERMAN ALONSO;337
BENAVIDES SIERRA DANIEL ANDRES;9
BEJARANO RAMOS LUZ ANGELICA;28
BECERRA LEON LUZ DARY;47
BARRETO OCHOA ROBERT ALBERTO;0
BAREÑO FRANCO ELVER RICARDO;34
BAQUERO LARA SILVIA NOHELBA;7
AYALA BERNAL JOSE MESIAS;0
AUTOVOL PROFESSIONAL S.A.S;0
AUTOPARTES J&M SUÁREZ S.A.S;18
ARMERO MORALES SANDRA MILENA;5
ARIESCA FILTROS & LUBRICANTES S.A.S;17
AREVALO LOPEZ WALTER;0
AREVALO CABRA WILMER;0
ARAGON HENAO FERNANDO ANDRES;0
ANAYA OLIVEROS DIANA FERNANDA;62
ALVAREZ RUIZ LILIANA;44
ALONSO GONZALEZ GONZALEZ;0
ALBERTO TORRES CARLOS ALFREDO;130
AGROFILTRACIONES R.M. SAS;115
AGROFILTER DE LA SABANA SAS;0
ABASTECEDORA NACIONAL DE ESTIBAS ANALDES S A;30
LUBRYREPUESTOS LR S.A.S.;3
WM FILTERS SAS;216
VELASCO VEGA AURA STELLA;124
VARGAS SALAMANCA LUIS ANGEL;0
TRATERCOL INGENIERIA DE TRATAMIENTOS TERMICOS S.A.S.;0
TRACTOCAD S EN C S;891
TECNILUBRICANTES GYG S.A.S;236
TECNIAUTOAMERICANA S.A.S.;15
TECNI.MOTOS GL S.A.S.;165
SUAREZ OJEDA IVAN RICARDO;110
SMART & GREEN ENERGY S.A.S.;0
SILVA VARGAS FABIO EDUARDO;219
SERVILLANTAS JAMUNDI S.A.S;224
SARMIENTO CALDERON JOSE RAUL;0
S.S. UP INVERSIONES SAS;0
ROMERO BONILLA MARIN;2835
RIVAS MARTINEZ CARLOS EDUARDO;99
RINCON RIVEROS ORLANDO;10
REPRESENTANTE SEGURIDAD GAS S. A. S.;110
RATIVA ORLANDO ALBERTO;176
PRO-MOTORS S A S;0
PIRACOCA JIMENEZ HECTOR EMILIO;170
PEREZ PLAZAS YILMER;850
OSCAR FERNANDO PEÑA GUTIERREZ;220
OCCIDENTAL DE SERVICIOS Y REPUESTOS AAA SAS;0
MAX OIL SAS;301
MATALLANA BALLESTEROS MAURICIO ANTONIO;75
MARTEXA C I S A S;0
LUBRISERVICIOS RETEN SUR S.A.S;372
LUBRIREPUESTOS YUMBO JRC S.A.S;948
LUBRIPARTS LYL S.A.S;2068
LUBRIKARS S.A.S;0
LUBRICANTES Y FILTROS LA SEXTA AVENIDA S.A.S.;76
LUBRICANTES Y FILTROS J J S.A.S;653
LUBRICANTES SAN ANTONIO SAS;173
LUBRICANTES PEPO S.A.S;774
LUBRICANTES LA ESTRELLA FACA S.A.S.;2908
LUBRICANTES DIDAMAR S.A.S;0
LUBRICANTES CZ S.A.S.;1451
LEON MOYANO JAVIER MAURICIO;55
JEREZ BUITRAGO JHON FREDY;110
INVERSIONES BOGOTA MOTORS SAS;935
INGEFILTERS COLOMBIA SAS;669
INDUSTRIAS CARDENAS FIRE SAS;0
INDUSTRIA SUPERFILT S.A.S;140
IBAÑEZ ALFONSO EFRAIN;0
HUERTAS ORTEGA CESAR MANUEL;433
HOLGIN DIAZ ADALBERTO;1063
VICTOR ALONSO HERRERA QUINTERO;187
GUTIERREZ ROJAS JOHAN FELIPE;55
GRISALES MESA EDWARD HERNAN;3087
GRAND FILTERS EU;0
GONZALEZ SALINAS EDWIN ARLEY;0
GOMEZ CERON LUDIVIA;510
GASODISEL SABANA S.A.S;42
GALEANO VELASQUEZ MARIA DACIER;110
G C FILTERS SAS;157
FILTROS Y FILTROS S.A.S.;895
FILCENTER S A S;39
DOCEL RAMIREZ JUAN CARLOS;120
DISTRIBUIDORA IMALBESTOS SAS;220
DISTRIBUIDORA HERCA ASOCIADOS SAS;964
DISTRIBUCIONES ALVARO CORREA S.A.S.;0
DIRECCIONES HIDRAULICAS EL MONO SAS;110
DACAR  FILTROS S.A.S.;1580
COOPERATIVA VALLECAUCANA DE TRANSPORTADORES;4263
COOPERATIVA INTEGRAL DE TRANSPORTADORES TAXIS EL TRIUNFO;1305
COMERCIALIZADORA INTERNACIONAL CALITRADE SOCIEDAD POR ACCIONES S;110
COLMENARES CELY MARIA DE JESUS;633
CERON OCHOA MAGNOLIA;433
CARO CASTELBLANCO LUIS ALEJANDRO;196
AUTOFILTROS Y PARTES GONZA MOTORS SAS;65
AMERICAN FILTERS OIL SAS;48
AMAYA BERNAL VICTOR ANTONIO;391
AGROFILTER LTDA;476
ANDINA DE TRANSMISIONES S.A.S;195
PRUEBA JUAN;1475
GUERRERO DIAZ CARLOS AUGUSTO;115`;

const CUSTOM_NAME_MAPPINGS: { [key: string]: string } = {
  "MOLANO BARRIOS LAURA MELISSA": "LAURA MELISSA MOLANO BARRIOS",
  "FERRETERIA INDUSTRIAL SOLUFER S.A.S.": "SOLUFER S.A.S",
  "SERVICIOS INTEGRALES EN LUBRICACIÓN EN MAQUINARIA S.A.S.": "SERVICIOS INTEGRALES EN LUBRICACIÓN DE MAQUINARIA S.A.S.",
  "TIBAVISCO VELOZA SERGIO LEONARDO": "TIBAVIZCO VELOZA SERGIO LEONARDO",
  "NIETO SOLANO LIZETH PAOLA": "LIZETH PAOLA NIETO SOLANO",
  "HERRERA QUINTERO VICTOR ALONSO": "VICTOR ALONSO HERRERA QUINTERO"
};

const normalizeKey = (str: string) => {
  let mapped = str.trim();
  if (CUSTOM_NAME_MAPPINGS[mapped]) {
    mapped = CUSTOM_NAME_MAPPINGS[mapped];
  }
  return mapped.toUpperCase().replace(/[^A-Z0-9]/g, '');
};

const parseDataFromCSVs = (): { clients: Client[], points: ClientPoints[] } => {
  const clientsLines = RAW_CLIENTS_CSV.trim().split('\n');
  const pointsLines = RAW_POINTS_CSV.trim().split('\n');
  
  const clients: Client[] = [];
  const pointsMap = new Map<string, number>();

  const pointsStart = pointsLines[0].startsWith('Punto de venta') ? 1 : 0;
  for (let i = pointsStart; i < pointsLines.length; i++) {
    const line = pointsLines[i].trim();
    if (!line) continue;
    const parts = line.split(';');
    if (parts.length >= 2) {
      const posName = parts[0].trim();
      const pts = parseInt(parts[1].trim()) || 0;
      pointsMap.set(normalizeKey(posName), pts);
    }
  }

  const clientsStart = clientsLines[0].startsWith('Tipo de cliente') ? 1 : 0;
  const points: ClientPoints[] = [];

  for (let i = clientsStart; i < clientsLines.length; i++) {
    const line = clientsLines[i].trim();
    if (!line) continue;
    
    const parts = line.split(';');
    if (parts.length >= 4) {
      const type = parts[0].trim() as ClientType;
      const businessId = parts[1].trim();
      const pointOfSale = parts[2].trim();
      const password = parts[3].trim();
      
      if (pointOfSale && password) {
        clients.push({
          id: `c_${i}`,
          businessId,
          pointOfSale,
          password,
          type
        });
        
        const normalizedPOS = normalizeKey(pointOfSale);
        const pts = pointsMap.get(normalizedPOS);

        points.push({
          pointOfSale,
          points: pts !== undefined ? pts : DEFAULT_POINTS
        });
      }
    }
  }
  return { clients, points };
};

const { clients: parsedClients, points: parsedPoints } = parseDataFromCSVs();

const INITIAL_DATA: Database = {
  clients: parsedClients,
  points: parsedPoints,
  rewards: REWARDS_DATA,
  orders: []
};

export const getDatabase = (): Database => {
  const globalOrdersStored = localStorage.getItem(GLOBAL_ORDER_HISTORY_KEY);
  const globalOrders: OrderLog[] = globalOrdersStored ? JSON.parse(globalOrdersStored) : [];

  const stored = localStorage.getItem(DB_KEY);
  if (!stored) {
    const data = { ...INITIAL_DATA, orders: globalOrders };
    localStorage.setItem(DB_KEY, JSON.stringify(data));
    return data;
  }
  const db = JSON.parse(stored);
  db.orders = globalOrders; 
  
  return db;
};

export const saveDatabase = (data: Database) => {
  localStorage.setItem(DB_KEY, JSON.stringify(data));
};

export const resetDatabase = (): Database => {
  localStorage.removeItem(DB_KEY);
  return getDatabase();
};

export const updateClientPoints = (pointOfSale: string, newPoints: number) => {
  const db = getDatabase();
  const index = db.points.findIndex(p => p.pointOfSale === pointOfSale);
  if (index !== -1) {
    db.points[index].points = newPoints;
    saveDatabase(db);
  }
};

export const deductPoints = (pointOfSale: string, amount: number): boolean => {
  const db = getDatabase();
  const clientPoints = db.points.find(p => p.pointOfSale === pointOfSale);
  
  if (clientPoints && clientPoints.points >= amount) {
    clientPoints.points -= amount;
    saveDatabase(db);
    return true;
  }
  return false;
};

export const addOrder = (order: OrderLog) => {
    const db = getDatabase();
    if (!db.orders) db.orders = [];
    db.orders.push(order);
    saveDatabase(db);

    const globalOrdersStored = localStorage.getItem(GLOBAL_ORDER_HISTORY_KEY);
    const globalOrders: OrderLog[] = globalOrdersStored ? JSON.parse(globalOrdersStored) : [];
    globalOrders.push(order);
    localStorage.setItem(GLOBAL_ORDER_HISTORY_KEY, JSON.stringify(globalOrders));
};

export const getClients = () => getDatabase().clients;
export const getPoints = (pointOfSale: string) => getDatabase().points.find(p => p.pointOfSale === pointOfSale)?.points || 0;
export const getRewards = () => getDatabase().rewards;
export const getOrders = () => getDatabase().orders;
