import { Reward } from '../types';

export const REWARDS_DATA: Reward[] = [
  {
    id: "rw_001",
    name: "Camiseta Gulf MCO",
    description: "Camiseta de algodón premium con diseño icónico de Gulf para motociclistas.",
    pointsPareto: 50,
    pointsNormal: 25,
    imageUrls: ["https://i.postimg.cc/VkB5XM1z/Camiste-moto-Model.png"],
    category: "Ropa",
    popularity: 90,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_002",
    name: "Camiseta Gulf PCMO",
    description: "Vístete con los colores de la victoria. Ideal para uso diario o eventos automotrices.",
    pointsPareto: 50,
    pointsNormal: 25,
    imageUrls: ["https://i.postimg.cc/pLYyK8xx/Camiste-Carro-Model.png"],
    category: "Ropa",
    popularity: 85,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_003",
    name: "Gorra GULF - Prolub",
    description: "Accesorio indispensable para complementar tu estilo Gulf.",
    pointsPareto: 17,
    pointsNormal: 8,
    imageUrls: ["https://i.postimg.cc/sfvKjPdk/Gorra-Cerrada-gulf-prolub.png"],
    category: "Accesorios",
    popularity: 70,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_004",
    name: "Licuadora 6 Velocidades",
    description: "Prepara los mejores batidos y cócteles para celebrar cada victoria de tu selección.",
    pointsPareto: 320,
    pointsNormal: 160,
    imageUrls: ["https://i.postimg.cc/8760MGYy/Licuadora.webp"],
    category: "Electrodomésticos",
    popularity: 80,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_005",
    name: "Picatodo Negro",
    description: "Pica los ingredientes para tus pasabocas tan rápido como un contragolpe letal.",
    pointsPareto: 147,
    pointsNormal: 73,
    imageUrls: ["https://i.postimg.cc/DSXMLhNx/Picatodo.webp"],
    category: "Electrodomésticos",
    popularity: 75,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_006",
    name: "Freidora de aire 4 Litros",
    description: "Snacks crujientes y saludables para el medio tiempo, sin perderte ni un segundo del partido.",
    pointsPareto: 463,
    pointsNormal: 231,
    imageUrls: ["https://i.postimg.cc/7fcR5hKF/Freidora-de-aire-4-Litros.webp"],
    category: "Electrodomésticos",
    popularity: 95,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_007",
    name: "Cafetera Eléctrica 12 Tazas He7031a Negro",
    description: "Mantente despierto en todos los partidos, incluso en los de la madrugada. Energía para gritar gol.",
    pointsPareto: 349,
    pointsNormal: 175,
    imageUrls: ["https://i.postimg.cc/xXz4MQZg/Cafetera-Electrica-12-Tazas-He7031a-Negro.webp"],
    category: "Electrodomésticos",
    popularity: 88,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_008",
    name: "Olla Eléctrica Multifunción",
    description: "Prepara un banquete de campeones mientras disfrutas de la final del Mundial.",
    pointsPareto: 533,
    pointsNormal: 267,
    imageUrls: ["https://i.postimg.cc/TpSsK1tF/Olla-Electrica-Multifuncion.jpg"],
    category: "Electrodomésticos",
    popularity: 82,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_009",
    name: "Sanduchera Panini",
    description: "Sándwiches calientes y listos para el pitazo inicial. El mejor refuerzo para tu hambre.",
    pointsPareto: 133,
    pointsNormal: 66,
    imageUrls: ["https://i.postimg.cc/hfwYXv2w/Sanduchera-Panini.webp"],
    category: "Electrodomésticos",
    popularity: 78,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_010",
    name: "Sanduchera Eléctrica 2 Puestos",
    description: "Doble porción para compartir con tu compañero de tribuna en casa.",
    pointsPareto: 107,
    pointsNormal: 53,
    imageUrls: ["https://i.postimg.cc/TpSsK1ts/Sanduchera-Electrica-2-Puestos.webp"],
    category: "Electrodomésticos",
    popularity: 76,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_011",
    name: "Horno Electrico",
    description: "Calienta tus snacks y mantén la temperatura del partido al máximo nivel.",
    pointsPareto: 295,
    pointsNormal: 147,
    imageUrls: ["https://i.postimg.cc/Ln7WJ5xQ/Horno-Electrico.jpg"],
    category: "Electrodomésticos",
    popularity: 84,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_012",
    name: "Horno Microondas de Mesa",
    description: "Comida lista en tiempo récord, para que no te pierdas ni una jugada de peligro.",
    pointsPareto: 492,
    pointsNormal: 246,
    imageUrls: ["https://i.postimg.cc/2VJt1y0c/Horno-Microondas-de-Mesa.jpg"],
    category: "Electrodomésticos",
    popularity: 87,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_013",
    name: "Ventilador De Piso",
    description: "Mantén la frescura cuando el partido se ponga candente en los últimos minutos.",
    pointsPareto: 332,
    pointsNormal: 166,
    imageUrls: ["https://i.postimg.cc/kBZH2GTT/Ventilador-De-Piso.jpg"],
    category: "Electrodomésticos",
    popularity: 72,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_014",
    name: "Ventilador 3 en 1",
    description: "Refresca el ambiente en la sala mientras tu equipo suda la camiseta en la cancha.",
    pointsPareto: 267,
    pointsNormal: 133,
    imageUrls: ["https://i.postimg.cc/Mv4LnH95/Ventilador-3-en-1.jpg"],
    category: "Electrodomésticos",
    popularity: 74,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_015",
    name: "Plancha Para Ropa vertical",
    description: "Tu camiseta de la selección siempre impecable, lista para salir a celebrar.",
    pointsPareto: 244,
    pointsNormal: 122,
    imageUrls: ["https://i.postimg.cc/7fcR5hKX/Plancha-Para-Ropa-vertical.webp"],
    category: "Electrodomésticos",
    popularity: 70,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_016",
    name: "Plancha De Vapor Ligera",
    description: "Elimina las arrugas de tu uniforme de hincha con la precisión de un tiro libre.",
    pointsPareto: 147,
    pointsNormal: 73,
    imageUrls: ["https://i.postimg.cc/zVMQyvxS/Plancha-De-Vapor-Ligera.webp"],
    category: "Electrodomésticos",
    popularity: 68,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_017",
    name: "Wafflera",
    description: "Desayunos de campeones para los partidos mañaneros del Mundial.",
    pointsPareto: 147,
    pointsNormal: 73,
    imageUrls: ["https://i.postimg.cc/YhVPv0dz/Wafflera.webp"],
    category: "Electrodomésticos",
    popularity: 81,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_018",
    name: "Nevera Convencional 211 Litros Brutos",
    description: "Mantén tus bebidas heladas para celebrar cada gol como se debe.",
    pointsPareto: 1733,
    pointsNormal: 867,
    imageUrls: ["https://i.postimg.cc/XphPrqsw/Nevera-Convencional-211-Litros-Brutos.jpg"],
    category: "Electrodomésticos",
    popularity: 85,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_019",
    name: "Nevera No Frost 249 L",
    description: "Espacio de sobra para las provisiones de toda la fase de grupos.",
    pointsPareto: 2133,
    pointsNormal: 1067,
    imageUrls: ["https://i.postimg.cc/rKbHDsfx/Nevera-No-Frost-249-L.jpg"],
    category: "Electrodomésticos",
    popularity: 88,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_020",
    name: "Nevera No Frost 389 L",
    description: "El estadio de tus bebidas. Capacidad gigante para la gran final.",
    pointsPareto: 2533,
    pointsNormal: 1267,
    imageUrls: ["https://i.postimg.cc/WhKydz5Z/Nevera-No-Frost-389-L.jpg"],
    category: "Electrodomésticos",
    popularity: 90,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_021",
    name: "Lavadora Carga Superior 15 kg",
    description: "Lava las camisetas de toda la hinchada después de una celebración épica.",
    pointsPareto: 3873,
    pointsNormal: 1937,
    imageUrls: ["https://i.postimg.cc/3d6qkNtv/Lavadora-Carga-Superior-15-kg.webp"],
    category: "Electrodomésticos",
    popularity: 92,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_022",
    name: "Lavadora Carga Superior 11 kg (24lb)",
    description: "Tu uniforme de la suerte siempre limpio y listo para el próximo encuentro.",
    pointsPareto: 2444,
    pointsNormal: 1222,
    imageUrls: ["https://i.postimg.cc/rKbHDsft/Lavadora-Carga-Superior-11-kg-(24lb).webp"],
    category: "Electrodomésticos",
    popularity: 89,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_023",
    name: "Sofá cama",
    description: "El mejor asiento del estadio está en tu sala. Comodidad total para ver el Mundial.",
    pointsPareto: 944,
    pointsNormal: 472,
    imageUrls: ["https://i.postimg.cc/9rSkD0L4/Sofa-cama.jpg"],
    category: "Hogar",
    popularity: 83,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_024",
    name: "Juego de comedor 6 puestos",
    description: "Reúne a tu equipo titular para disfrutar de una buena comida antes del partido.",
    pointsPareto: 1111,
    pointsNormal: 556,
    imageUrls: ["https://i.postimg.cc/BXyzjbmP/Juego-de-comedor-6-puestos.jpg"],
    category: "Hogar",
    popularity: 86,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_025",
    name: "Juego de vajilla 4 puestos",
    description: "Sirve la pasión del fútbol en cada comida con tu familia.",
    pointsPareto: 133,
    pointsNormal: 67,
    imageUrls: ["https://i.postimg.cc/pp7Smrsh/Juego-de-vajilla-4-puestos.jpg"],
    category: "Hogar",
    popularity: 79,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_026",
    name: "Batería de ollas",
    description: "Equipa tu cocina como un verdadero director técnico prepara su estrategia.",
    pointsPareto: 267,
    pointsNormal: 133,
    imageUrls: ["https://i.postimg.cc/ZC0gYpxr/Bateria-de-ollas.webp"],
    category: "Hogar",
    popularity: 82,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_027",
    name: "Reloj Garmin Vivoactive 5 Marfil",
    description: "Mide tus pulsaciones en la tanda de penales y controla tu rendimiento como un profesional.",
    pointsPareto: 2132,
    pointsNormal: 1066,
    imageUrls: ["https://i.postimg.cc/Vd5TsnWX/Reloj-Garmin-Vivoactive-5-Marfil.jpg"],
    category: "Tecnología",
    popularity: 94,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_028",
    name: "Televisor Challenger 32” LED",
    description: "No te pierdas ningún detalle del partido desde la comodidad de tu cuarto.",
    pointsPareto: 949,
    pointsNormal: 475,
    imageUrls: ["https://i.postimg.cc/F71qF3Vy/Televisor-Challenger-32-LED.webp"],
    category: "Tecnología",
    popularity: 85,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_029",
    name: "Televisor 40” LED UHD 4K",
    description: "Resolución de campeonato para ver cada jugada polémica con claridad.",
    pointsPareto: 2000,
    pointsNormal: 1000,
    imageUrls: ["https://i.postimg.cc/2V3Jjh7v/Televisor-40-LED-UHD-4K.webp"],
    category: "Tecnología",
    popularity: 88,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_030",
    name: "Televisor 43” LED UHD 4K",
    description: "Siente que estás en el estadio con colores vivos y definición de primera.",
    pointsPareto: 2667,
    pointsNormal: 1333,
    imageUrls: ["https://i.postimg.cc/kBDZMKvb/Televisor-43-LED-UHD-4K.webp"],
    category: "Tecnología",
    popularity: 90,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_031",
    name: "Televisor 50” LED UHD 4K",
    description: "Una pantalla gigante para vivir la emoción del Mundial en tamaño real.",
    pointsPareto: 3467,
    pointsNormal: 1733,
    imageUrls: ["https://i.postimg.cc/9rzSXZYR/Televisor-50-LED-UHD-4K.webp"],
    category: "Tecnología",
    popularity: 92,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_032",
    name: "Televisor 65” LED UHD 4K",
    description: "El estadio en tu sala. La experiencia definitiva para la final del mundo.",
    pointsPareto: 4444,
    pointsNormal: 2222,
    imageUrls: ["https://i.postimg.cc/Lnh74L3g/Televisor-65-LED-UHD-4K.webp"],
    category: "Tecnología",
    popularity: 95,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_033",
    name: "Barra de sonido",
    description: "Escucha el cántico de la hinchada y el silbato del árbitro como si estuvieras allí.",
    pointsPareto: 1507,
    pointsNormal: 753,
    imageUrls: ["https://i.postimg.cc/PPNcfYQL/Barra-de-sonido.webp"],
    category: "Tecnología",
    popularity: 89,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_034",
    name: "Parlante Clip 5 JBL",
    description: "Parlante portátil ultra resistente para llevar tu música a todas partes.",
    pointsPareto: 378,
    pointsNormal: 189,
    imageUrls: ["https://i.postimg.cc/D8mDfLPm/Parlante-Clip-5-JBL.webp"],
    category: "Tecnología",
    popularity: 91,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_035",
    name: "Parlante K-SPK300D Negro",
    description: "Potencia de estadio para que tus celebraciones se escuchen en todo el barrio.",
    pointsPareto: 1107,
    pointsNormal: 553,
    imageUrls: ["https://i.postimg.cc/ykW56cyx/Parlante-K-SPK300D-Negro.webp"],
    category: "Tecnología",
    popularity: 86,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_036",
    name: "Audífonos Deportivos Inalámbricos Bluetooth 5.3",
    description: "Libertad de movimiento y sonido nítido para tus entrenamientos.",
    pointsPareto: 133,
    pointsNormal: 67,
    imageUrls: ["https://i.postimg.cc/SJj5QCfx/Audifonos-Deportivos-Inalambricos-Bluetooth-5-3.webp"],
    category: "Tecnología",
    popularity: 84,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_037",
    name: "Audífonos Diadema Bluetooth con SD y Radio",
    description: "Variedad de opciones de escucha con estos audífonos versátiles.",
    pointsPareto: 133,
    pointsNormal: 67,
    imageUrls: ["https://i.postimg.cc/1f4TRwrt/Audifonos-Diadema-Bluetooth-con-SD-y-Radio.webp"],
    category: "Tecnología",
    popularity: 82,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_038",
    name: "Audífonos de diadema JBL Bluetooth",
    description: "Calidad de sonido JBL legendaria sin cables.",
    pointsPareto: 377,
    pointsNormal: 188,
    imageUrls: ["https://i.postimg.cc/8js3kMmp/Audifonos-de-diadema-JBL-Bluetooth.webp"],
    category: "Tecnología",
    popularity: 90,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_039",
    name: "Mini Proyector WiFi y Bluetooth - Resolución nativa 1080P",
    description: "Cine en casa compacto con conectividad inalámbrica.",
    pointsPareto: 389,
    pointsNormal: 194,
    imageUrls: ["https://i.postimg.cc/tY7fRWNp/Mini-Proyector-Wi-Fi-y-Bluetooth-Resolucion-nativa-1080P.webp"],
    category: "Tecnología",
    popularity: 87,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_040",
    name: "Amazon Alexa",
    description: "Controla tu hogar con tu voz a través de Alexa.",
    pointsPareto: 400,
    pointsNormal: 200,
    imageUrls: ["https://i.postimg.cc/mthqZCys/Amazon-Alexa.webp"],
    category: "Tecnología",
    popularity: 93,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_041",
    name: "Aspiradora Robot",
    description: "Limpieza inteligente y autónoma para tus pisos.",
    pointsPareto: 980,
    pointsNormal: 490,
    imageUrls: ["https://i.postimg.cc/F71qF3VQ/Aspiradora-Robot.webp"],
    category: "Electrodomésticos",
    popularity: 85,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_042",
    name: "Patineta eléctrica Xiaomi Scooter 5 Max",
    description: "Movilidad urbana rápida y sostenible.",
    pointsPareto: 3667,
    pointsNormal: 1833,
    imageUrls: ["https://i.postimg.cc/GH9N3Gxn/Patineta-electrica-Xiaomi-Scooter-5-Max.webp"],
    category: "Deportes",
    popularity: 89,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_043",
    name: "Bicicleta Eléctrica 35kmh",
    description: "Recorre la ciudad con asistencia eléctrica y gran autonomía.",
    pointsPareto: 3222,
    pointsNormal: 1611,
    imageUrls: ["https://i.postimg.cc/hfhw4Tbk/Bicicleta-Electrica-35kmh.webp"],
    category: "Deportes",
    popularity: 91,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_044",
    name: "Portátil HP 14”",
    description: "Rendimiento y portabilidad para tus tareas diarias.",
    pointsPareto: 2199,
    pointsNormal: 1099,
    imageUrls: ["https://i.postimg.cc/qg1SdjyM/Portatil-HP-14.webp"],
    category: "Tecnología",
    popularity: 86,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_045",
    name: "Tablet SAMSUNG",
    description: "Versatilidad y entretenimiento en tus manos.",
    pointsPareto: 2133,
    pointsNormal: 1067,
    imageUrls: ["https://i.postimg.cc/6TMgNYnt/Tablet-SAMSUNG.webp"],
    category: "Tecnología",
    popularity: 88,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_046",
    name: "Tablet Lenovo",
    description: "Ideal para estudiar, trabajar o disfrutar contenidos multimedia.",
    pointsPareto: 1333,
    pointsNormal: 667,
    imageUrls: ["https://i.postimg.cc/MX9N8dV8/Tablet-Lenovo.jpg"],
    category: "Tecnología",
    popularity: 85,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_047",
    name: "Samsung Galaxy A16 · 256 GB · 8 GB RAM",
    description: "Smartphone con gran capacidad y rendimiento fluido.",
    pointsPareto: 1200,
    pointsNormal: 600,
    imageUrls: ["https://i.postimg.cc/G9XV1qGR/Samsung-Galaxy-A16-256-GB-8-GB-RAM.webp"],
    category: "Tecnología",
    popularity: 89,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_048",
    name: "Samsung Galaxy A36 · 256 GB · 8 GB RAM",
    description: "Captura cada detalle con su avanzado sistema de cámaras.",
    pointsPareto: 1667,
    pointsNormal: 833,
    imageUrls: ["https://i.postimg.cc/14v2ZJw1/Samsung-Galaxy-A36-256-GB-8-GB-RAM.webp"],
    category: "Tecnología",
    popularity: 91,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_049",
    name: "iPhone 13 · 128 GB",
    description: "El icónico iPhone 13 con rendimiento de vanguardia.",
    pointsPareto: 4000,
    pointsNormal: 2000,
    imageUrls: ["https://i.postimg.cc/fk8phBmn/i-Phone-13-128-GB.webp"],
    category: "Tecnología",
    popularity: 95,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_050",
    name: "iPhone 15 · 128 GB",
    description: "La última tecnología de Apple al alcance de tus puntos.",
    pointsPareto: 5067,
    pointsNormal: 2533,
    imageUrls: ["https://i.postimg.cc/G9XV1qY6/i-Phone-15-128-GB.jpg"],
    category: "Tecnología",
    popularity: 98,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_051",
    name: "Celular SAMSUNG Galaxy A17 256 GB 8 GB RAM Azul",
    description: "Nuevo diseño y potencia superior en color azul.",
    pointsPareto: 1333,
    pointsNormal: 667,
    imageUrls: ["https://i.postimg.cc/bdmWj3kX/Celular-SAMSUNG-Galaxy-A17-256-GB-8-GB-RAM-Azul.png"],
    category: "Tecnología",
    popularity: 87,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_052",
    name: "Celular MOTOROLA G55",
    description: "Fiabilidad y excelente relación calidad-precio.",
    pointsPareto: 1333,
    pointsNormal: 667,
    imageUrls: ["https://i.postimg.cc/xq6hStH7/Celular-MOTOROLA-G55.webp"],
    category: "Tecnología",
    popularity: 84,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_053",
    name: "Celular MOTOROLA G56 5G 256 GB 8 GB RAM Azul Marino",
    description: "Conexión 5G ultrarrápida y gran almacenamiento.",
    pointsPareto: 1444,
    pointsNormal: 722,
    imageUrls: ["https://i.postimg.cc/14v2ZJ6Y/Celular-MOTOROLA-G56-5G-256-GB-8-GB-RAM-Azul-Marino.webp"],
    category: "Tecnología",
    popularity: 86,
    dateAdded: "2026-05-15"
  },
  {
    id: "rw_054",
    name: "Ahumador y Asador de Barril Mediano 20 Lbs",
    description: "El MVP del tercer tiempo. Prepara los mejores asados para celebrar con tu hinchada.",
    pointsPareto: 667,
    pointsNormal: 333,
    imageUrls: ["https://i.postimg.cc/5jsTMnvR/Ahumador-y-Asador-de-Barril-Mediano-20-Lbs.webp"],
    category: "Hogar",
    popularity: 85,
    dateAdded: "2026-05-15"
  }
];
