const fs = require('fs');

const newPointsCsv = `Punto de venta;Puntos disponibles
COLMENARES CELY MARIA DE JESUS;207
TECNILUBRICANTES GYG S.A.S;88
AGROFILTER LTDA;0
SMART & GREEN ENERGY S.A.S.;0
CARO CASTELBLANCO LUIS ALEJANDRO;73
HUERTAS ORTEGA CESAR MANUEL;101
JEREZ BUITRAGO JHON FREDY;70
DACAR FILTROS S.A.S.;114
PRIETO CARDENAS RONAL FABIAN;0
ANAYA OLIVEROS DIANA FERNANDA;0
FC POWER SOLUTIONS SAS;40
SILVA VARGAS FABIO EDUARDO;0
COMERCIALIZADORA FILT REP LTDA;54
RIVAS MARTINEZ CARLOS EDUARDO;34
MATALLANA BALLESTEROS MAURICIO ANTONIO;43,5
DOSMOPAR SOCIEDAD POR ACCIONES SIMPLIFICADA;0
MOLANO BARRIOS LAURA MELISSA;24
GARCIA REYES GONZALO EDUARDO;71
BERNAL PACHON GERMAN ALONSO;19
LUBRISERVICIOS RETEN SUR S.A.S;60
TECNI.MOTOS GL S.A.S.;0
COMERCIALIZADORA INTERNACIONAL CALITRADE SOCIEDAD POR ACCIONES S;0
AGROFILTRACIONES R.M. SAS;0
FILTROS Y ACEITES SANTA MARTA S.A.S.;60
GOMEZ RODRIGUEZ FERNANDO;0
MELO OLMOS SERGIO ANDRES;27
AMERICAN FILTERS OIL SAS;0
ROZO MORA JORGE ALGEMIRO;0
GRAND FILTERS EU;0
CALDERON URREGO ANDRES ARTURO;0
TECNIAUTOAMERICANA S.A.S.;0
LUBRICANTES VALLADOLID S.A.S.;0
COLOMBIANA DE ACEITES Y FILTROS INDUSTRIALES S.A.S;0
ROJAS PEREZ JOSE ORLANDO;0
BRAVO GRISALES LUZ DERLY;22,75
PIRACOCA JIMENEZ HECTOR EMILIO;0
GUALTEROS LOVERA FERNANDO;0
MURCIA ALBORNOZ JUAN PABLO;0
LUBRICANTES GARCIA NOPE SAS;58
DONDE ALEJO LUBRICENTRO SAS;0
CORO JORGE IVAN;19,17006
PAULO RICHARD RAMOS DAZA;0
OSCAR FERNANDO PE A GUTIERREZ;0
GOMEZ CERON ARCELINA MARGOTH;59
SUAREZ OJEDA IVAN RICARDO;55
RAMIREZ MIRQUEZ MOISES;7
SILVA LOPEZ OSCAR IVAN;0
HERNANDEZ SACRISTAN FABIAN ROLANDO;0
SALINAS REYES GESLY YURANY;0
BIOFILTER LTDA;10
RODRIGUEZ PULIDO LUZ DARY;0
QUINTANA RIASCOS JOSE FERNANDO;16
MONTACARGAS EN SIBERIA S A S;0
LUBRICANTES LA ROCA S.A.S;10
DOCEL RAMIREZ JUAN CARLOS;0
SANCHEZ PALACIO ANGEL HUMBERTO;0
LUBRICANTES Y FILTROS LA SEXTA AVENIDA S.A.S.;21
MASFILTER Y LUBRICANTES SAS;0
DIRECCIONES HIDRAULICAS EL MONO SAS;0
JARAMILLO QUINTERO JAIRO;7
FIZA S A S;0
VALLES ABELLO ARMANDO;0
LUBRIMOTOR GRASAS Y ACEITES S.A.S LUBRIMOTOR S.A.S;0
PEREZ BAUTISTA FRANCISCO ALEJANDRO;0
GONZALEZ MATAMOROS MARIA DEL TRANSITO;0
DISTRIBUIDORA DE FILTROS Y LUBRICANTES SR LTDA;0
PARADA BEATRIZ;0
GALARZA CARDONA ANDRES FELIPE;0
RODRIGUEZ TROCHEZ ENELIA;0
LUBRICENTRO SANTA ROSA SAS;0
ALBERTO TORRES CARLOS ALFREDO;20
DIAZ PINZON LUIS FERNANDO;13
TRANSPORTES Y SERVICIOS INTEGRAL S.A.S;0
ELECTRICOS Y FERRETERIA GERVEL & COMPA IA LTDA;0
MERCADO RAMIREZ JHON WAYNER;17
FILTROS Y LUBRICANTES H Y H SAS;22
VILLANUEVA JAMIR;31,02036
S.S. UP INVERSIONES SAS;0
G & O CAMBIO Y DISTRIBUCION DE ACEITE MONTALLANTAS SAS;0
COMERCIALIZADORA FILT REP LTDA;54
ESCOBAR CARDONA CESAR AUGUSTO;0
HERNANDO RINCON CABRA;4
CASA DEL FILTRO CH A S.A.S;0
RINCON MORENO BRAYAN EDUARDO;0
LUBRIMARKET FILTROS Y LUBRICANTES SAS;0
AREVALO CABRA WILMER;0
TRATERCOL INGENIERIA DE TRATAMIENTOS TERMICOS S.A.S.;0
MORALES MARTINEZ LEIDY MARCELA;0
REPRESENTANTE SEGURIDAD GAS S. A. S.;55
GUERRERO DIAZ CARLOS AUGUSTO;60
INDUSTRIAS CARDENAS FIRE SAS;0
SALAS ROSERO EDITH LUCIA;0
FERRETERIA INDUSTRIAL SOLUFER S.A.S.;0
LINARES CABRA RUTH ADRIANA;0
RODRIGUEZ PULIDO ANA BELISA;35
ALVAREZ RUIZ LILIANA;0
TECNOLUBES SAS;0
CRUZ AVILA JOSE JOAQUIN;0
ZAPATA GIRALDO MARTHA ROCIO;0
CIFUENTES SABOGAL PLUTARCO;24,5
MONTES GUILLERMO ALVARO JOSE;9,25
CORTES SANCHEZ GUSTAVO ADOLFO;0
PEREZ SEGURA JOSE EDUARDO;0
CENTRO DE MANTENIMIENTO AUTOMOTRIZ RD S.A.S.;0
COOPERATIVA DE TRANSPORTADORES FLOTA PALMIRA;0
DISTRIGAUSDA SAS;17
MOLINA TORRES NIDIA ESPERANZA;0
RIGO AUTOS CALI S.A.S;8
SERVITECA LUBRITECA 15 B S.A.S.;0
MERLO VANEGAS FLOR CRISTINA;0
CERON BUITRON PASTOR;0
LYC LUBRICANTES SAS;0
PRIETO CANTE CRISTIAN CAMILO;8
LOPEZ DIAZ GUSTAVO;0
HERNANDEZ ORTIZ LISSETTE;0
ROJAS GUATUSMAL BRENDA JOHANA;0
RIVERA BRAVA S.A.S.;0
OCAMPO BARRAGAN YESMIN CRISTINA;0
BECERRA LEON LUZ DARY;11
TRIANA ROJAS ANA CLOVIS;0
MUNDIAL DE FILTROS Y AUTOPARTESSAGA SAS;18
BEJARANO RAMOS LUZ ANGELICA;0
SERVICIOS INTEGRALES EN LUBRICACI N DE MAQUINARIA S.A.S.;0
BARE O FRANCO ELVER RICARDO;0
GUZMAN GOMEZ NESTOR DARIO;0
NEWMAN S CARS SAS;0
SAAVEDRA GONZALEZ JHON JAIRO;0
SU PROVEEDOR SUMINISTROS Y FERRETERIA S.A.S;0
ARIESCA FILTROS & LUBRICANTES S.A.S;0
DAZA GOMEZ JONATHAN SMITH;0
RINCON RIVEROS ORLANDO;0
GONZALEZ SALINAS JEIMMY CAROLINA;0
HIDRAULICOS J R S A S;22,89
AUTOPARTES J&M SU REZ S.A.S;0
HC SERVICE  S SAS;0
FORTALEZA CENTRO DE LUBRICACION SAS;0
ZAPATA GAMBINO WILSON JAVIER;5,17006
GOMEZ ESPITIA NELSON ARMANDO;0
TRANSPORTES LIMICIO LTDA;0
AGROFILTER DE LA SABANA SAS;0
GUTIERREZ ROJAS JOHAN FELIPE;0
LEON MOYANO JAVIER MAURICIO;55
LUBRICANTES SAN ANTONIO SAS;0
OCCIDENTAL DE SERVICIOS Y REPUESTOS AAA SAS;0
GALEANO VELASQUEZ MARIA DACIER;55
RAUL CASA AS PALACIOS;0
FLOREZ VENEGAS JUAN CARLOS;0
SIERRA MARTINEZ JOHN ALEJANDRO;0
VILLAMIL MARTINEZ JONATHAN;0
ABASTECEDORA NACIONAL DE ESTIBAS ANALDES S A;0
HERNANDEZ NI O LEOPOLDO;0
EDS TISQUESUSA S.A.S;0
VARGAS VASQUEZ MARY LUZELLA;0
MORALES GONZALEZ OCTAVIO;0
PRADA EDWIN CAMILO;0
TORNIFRENOS Y REPUESTOS OSORIO S.A.S.;0
RODRIGUEZ QUIROGA JOSE ALEXANDER;0
GUZMAN ROJAS JUAN SEBASTIAN;0
RODRIGUEZ ROMERO TANIA MARCELA;0
GOMEZ LEDESMA LUIS ARMANDO;0
COLOMBIANA DISTRIBUIDORA DE LUBRICANTES SAS;0
CRUZ OCHOA JULIO CESAR;0
LUBRICANTES Y BATERIAS WILCARS SAS;0
CAPERA LIDIA;0
SALDARRIAGA & CIA LTDA;0
CAICEDO CA ON INGRID MADALAIN;0
INSTITUTO TECNICO DE EDUCACION LABORAL Y MECANICO DE OCCIDENTE S;3
GONZALEZ SUAREZ LUIS ALFREDO;0
VISUM Y CIA LTDA;0
TRUCK FILERS JM S.A.S;13
QUINTERO KAREN ARABELLY;0
NI O ZAPATA BRYANT ESTIVEN;0
BOBCAT SERVICE SAS;46
ARMERO MORALES SANDRA MILENA;0
TIBAVISCO VELOZA SERGIO LEONARDO;14,51018
FILTROS AYZ S.A.S.;0
PARRA GOMEZ SERGIO GIOVANY;0
NEIRA LOPEZ LEONARDO MIGUEL;0
NELCAR DE OCCIDENTE S.A.S;4
VARGAS MARTINEZ ISMAEL ANTONIO;0
CENTRO DE LUBRICACION AUTOMOTRIZ S.A.S.;0
DIAZ MORENO OLGA PATRICIA;0
TORRES MORALES PAOLA ANDREA;0
BARRETO OCHOA ROBERT ALBERTO;0
RODRIGUEZ SILVA JAZMIN LORENA;0
BAQUERO LARA SILVIA NOHELBA;0
NU EZ MONROY ARMANDO;0
RODRIGUEZ BONILLA SORAIDA;0
LUBRIMARKAS R&D S.A.S;0
GARCIA MARTINEZ EDWIN ALEXANDER;0
DAZA BARBOSA CRISTIAN CAMILO;0
CUTA QUINTANA PEDRO ALONSO;0
MONGUI MEDINA JUAN CARLOS;0
SANCHEZ BARON MIGUEL ANTONIO;0
CARDENAS LOPEZ VIVIANA ANDREA;0
GUZMAN PINEDA YENIFFER;5,17006
ALONSO GONZALEZ GONZALEZ;0
LOPEZ GONZALEZ LUIS FERNANDO;0
PANQUEVA MONTOYA PATRICIO JAVIER;0
RINCON MONTOYA NELSON ENRIQUE;0
SANCHEZ AMAGUA A FABIAN JAIR;0
MONTACARGAS HARD CARGO SAS;0
MKTRONICA CAR SERVICE S.A.S;0
SERRANO CELY VELKYS SARIMA;0
AREVALO LOPEZ WALTER;0
OPERADOR LOGISTICO DG S.A.S;0
GUAYACAN GUEVARA ALBA INES;0
VARGAS GONZALEZ LUIS NELSON;0
SILVA BARBOSA BRIYITH NATALY;0
CONTRERAS MORENO LUZ ANGELA;0
TECNIPLANTAS AIRES Y BOMBAS SAS;0
LOSADA VALLEJO NICXON ALEJANDRO;0
MONTA O BAHAMON JULIAN DAVID;0
GOMEZ SALAZAR JOHN EDGAR;0
QUIROGA LEON RUTH NEYLA;0
ESCOBAR FRANCO JORGE HERMINSUL;0
GALINDO JULIO CESAR;0
GOMEZ MESSA JULIAN;0
GALEANO ALARCON MARCELA;0
CARDENAS MU OZ FLOR DE MARIA;0
MORENO CABALLERO NINA;0
CASTRO PARADA HELMER ERNESTO;0
LOSADA PACHON JOSE DANIEL;0
ARAGON HENAO FERNANDO ANDRES;0
ZAMORA VASQUEZ ELIECER;9
CUEVAS RODRIGUEZ YESID ADRIAN;0
LUBRIFILTROS MJ SAS;0
UMA A MARTINEZ VICTOR SAMIR;0
SERVICIOS AUTOMOTORES FLORIDA S.A.S.;4
FERNANDEZ PAYA ROSO FRANCISCO;0
NIETO SOLANO LIZETH PAOLA;5,17006
GONZALEZ SANNA ERICK;0
BENAVIDES SIERRA DANIEL ANDRES;0
AUTOVOL PROFESSIONAL S.A.S;0
LUBRICANTES G.V. SAS;0
MORENO CUCAITA JHON FREDDY;0
QUIROGA PAEZ NORBEY ALBERTO;0
AYALA BERNAL JOSE MESIAS;0
SERVITECH GROUP SAS;0
LOPEZ FORERO CRISTIAN CAMILO;0
LUBRICANTES LA ESTRELLA FACA S.A.S.;303
COOPERATIVA VALLECAUCANA DE TRANSPORTADORES;892
LUBRICANTES CZ S.A.S.;116,1003
FILTROS Y FILTROS S.A.S.;0
GRISALES MESA EDWARD HERNAN;0
ROMERO BONILLA MARIN;550
DISTRIBUIDORA HERCA ASOCIADOS SAS;0
COOPERATIVA INTEGRAL DE TRANSPORTADORES TAXIS EL TRIUNFO;195
HOLGIN DIAZ ADALBERTO;60
WM FILTERS SAS;843
FILCENTER S A S;696
PRO-MOTORS S A S;0
PEREZ PLAZAS YILMER;40
LUBRIREPUESTOS YUMBO JRC S.A.S;149,25
RATIVA ORLANDO ALBERTO;0
TRACTOCAD S EN C S;74
AMAYA BERNAL VICTOR ANTONIO;145
GOMEZ CERON LUDIVIA;166,8503
DISTRIBUCIONES ALVARO CORREA S.A.S.;0
LUBRICANTES PEPO S.A.S;139,34012
INDUSTRIA SUPERFILT S.A.S;0
CERON OCHOA MAGNOLIA;32,5
LUBRICANTES Y FILTROS J J S.A.S;69
DISTRIBUIDORA IMALBESTOS SAS;110
LUBRIKARS S.A.S;0
VELASCO VEGA AURA STELLA;0
MAX OIL SAS;55
GASODISEL SABANA S.A.S;4
G C FILTERS SAS;84
GONZALEZ SALINAS EDWIN ARLEY;0
LUBRIPARTS LYL S.A.S;155
AUTOFILTROS Y PARTES GONZA MOTORS SAS;46
SERVILLANTAS JAMUNDI S.A.S;23
INGEFILTERS COLOMBIA SAS;74
HERRERA QUINTERO VICTOR ALONSO;40
LUBRICANTES DIDAMAR S.A.S;0
VARGAS SALAMANCA LUIS ANGEL;0
MARTEXA C I S A S;0
DACAR FILTROS S.A.S.;114
INVERSIONES BOGOTA MOTORS SAS;275
IBA EZ ALFONSO EFRAIN;0`;

let dbContent = fs.readFileSync('services/db.ts', 'utf-8');

const startIdx = dbContent.indexOf('const RAW_POINTS_CSV = \`');
const endIdx = dbContent.indexOf('\`;', startIdx);

if (startIdx !== -1 && endIdx !== -1) {
    dbContent = dbContent.substring(0, startIdx) + 'const RAW_POINTS_CSV = \`' + newPointsCsv + dbContent.substring(endIdx);
    
    // Update DB_KEY
    dbContent = dbContent.replace(/const DB_KEY = 'gulf_prolub_db_v\d+';/, "const DB_KEY = 'gulf_prolub_db_v11';");
    
    fs.writeFileSync('services/db.ts', dbContent);
    console.log('Updated RAW_POINTS_CSV');
} else {
    console.log('Could not find RAW_POINTS_CSV');
}
